name: flutter_video_view
description: A view for video based on video_player and provides many basic functions.
version: 1.1.2
homepage: https://github.com/LiWenHui96
repository: https://github.com/LiWenHui96/flutter_video_view
issue_tracker: https://github.com/LiWenHui96/flutter_video_view/issues

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  battery_plus: ^2.1.0
  connectivity_plus: ^2.3.0
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  provider: ^6.0.0
  screen_brightness: ^0.2.1
  video_player: ^2.4.0
  volume_controller: ^2.0.3
  wakelock: ^0.6.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
