name: flutter_video_view
description: A view for video based on video_player and provides many basic functions.
version: 2.0.2+1
homepage: https://github.com/LiWenHui96
repository: https://github.com/LiWenHui96/flutter_video_view
issue_tracker: https://github.com/LiWenHui96/flutter_video_view/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  screen_brightness: ^1.0.0
  video_player: ^2.8.2
  volume_controller: ^2.0.0
  wakelock_plus: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
